export const MOCK_USER = {
  id: 1,
  name: "Jan Kowalski",
  email: "jan.kowalski@zaufajrzeczoznawcy.pl",
  role: "Rzeczoznawca mobilny",
  bitrix_id: 10
}

export const MOCK_DEALS = [
  {
    id: "ORDER-001",
    title: "Zlecenie nr. 301 - ŠKODA SUPERB",
    status: "in_progress", // To show RESUME button
    stage: "PREPAYMENT_INVOICE",
    scheduledDate: "2026-03-19T10:00:00",
    location: "Al. Jerozolimskie 109, 02-011 Warszawa",
    clientFirstName: "Mariusz",
    clientLastName: "Testowy",
    companyName: "Ayvens Fleet Management",
    clientPhone: "+48 790 469 341",
    vin: "TMBAN8NZ6TC021997",
    brand: "ŠKODA",
    model: "SUPERB Selection",
    year: "2025",
    color: "Silver",
    registrationNumber: "WI 746RH",
    mileage: "4320",
    fuelType: "MHEV Petrol",
    engineCapacity: "1498",
    enginePower: "150",
    gearboxType: "DSG 7-speed",
    driveType: "4×2",
    bodyType: "Hatchback",
    doorsCount: "5",
    seatsCount: "5",
    weight: "1673",
    firstRegistrationDate: "2025-11-30",
    inspectorName: "Test Appraiser",
  },
  {
    id: "ORDER-002",
    title: "Zlecenie nr. 302 - ŠKODA SUPERB",
    status: "new",
    stage: "NEW",
    scheduledDate: null,
    location: "Leszczyńskiego 4/29, 50-078 Wrocław",
    clientFirstName: "Anna",
    clientLastName: "Kowalska",
    companyName: "PKO Fleet Solutions",
    clientPhone: "+48 600 123 456",
    vin: "TMBAN8NZ6TC021997",
    brand: "ŠKODA",
    model: "SUPERB Selection",
    year: "2025",
    color: "Silver",
    registrationNumber: "WI 746RH",
    mileage: "4320",
    fuelType: "MHEV Petrol",
    engineCapacity: "1498",
    enginePower: "150",
    gearboxType: "DSG 7-speed",
    driveType: "4×2",
    bodyType: "Hatchback",
    doorsCount: "5",
    seatsCount: "5",
    weight: "1673",
    firstRegistrationDate: "2025-11-30",
    inspectorName: "Test Appraiser",
  }
]

export const MOCK_STAGES = [
  "Nowe zlecenie",
  "Ustalone oględziny", 
  "W trakcie inspekcji",
  "Zakończone",
  "Anulowane"
]
