export const MOCK_USER = {
  id: 1,
  name: "Jan Kowalski",
  email: "jan.kowalski@zaufajrzeczoznawcy.pl",
  role: "Rzeczoznawca mobilny",
  bitrix_id: 10
}

export const MOCK_DEALS = [
  {
    id: "213",
    title: "Wycena - BMW X5 2022",
    type: "WYCENA",
    stage: "Ustalone oględziny",
    scheduledDate: "2026-03-16T10:00:00",
    registrationNumber: "KR 12345",
    vin: "WBA12345678901234",
    brand: "BMW",
    model: "X5",
    year: "2022",
    color: "Czarny",
    fuelType: "BENZYNA",
    bodyType: "SUV",
    gearboxType: "AUTOMATYCZNA",
    mileage: "45000",
    clientFirstName: "Marek",
    clientLastName: "Nowak",
    clientPhone: "+48 600 123 456",
    clientEmail: "marek.nowak@gmail.com",
    location: "Kraków, ul. Floriańska 12",
    status: "scheduled"
  },
  {
    id: "214",
    title: "CFM - Toyota Corolla 2020",
    type: "CFM",
    stage: "Nowe zlecenie",
    scheduledDate: "2026-03-16T13:00:00",
    registrationNumber: "WA 98765",
    vin: "SB1K53AE90E123456",
    brand: "Toyota",
    model: "Corolla",
    year: "2020",
    color: "Srebrny",
    fuelType: "HYBRYDA",
    bodyType: "SEDAN",
    gearboxType: "CVT",
    mileage: "67000",
    clientFirstName: "Anna",
    clientLastName: "Wiśniewska",
    clientPhone: "+48 700 456 789",
    clientEmail: "anna.w@firma.pl",
    location: "Warszawa, ul. Marszałkowska 5",
    status: "scheduled"
  },
  {
    id: "215",
    title: "Wycena - Volkswagen Passat 2019",
    type: "WYCENA",
    stage: "Nowe zlecenie",
    scheduledDate: null,
    registrationNumber: "PO 54321",
    vin: "WVWZZZ3CZKE123456",
    brand: "Volkswagen",
    model: "Passat",
    year: "2019",
    color: "Biały",
    fuelType: "DIESEL",
    bodyType: "KOMBI",
    gearboxType: "MANUALNA",
    mileage: "112000",
    clientFirstName: "Piotr",
    clientLastName: "Kowalczyk",
    clientPhone: "+48 500 789 123",
    clientEmail: "piotr.k@gmail.com",
    location: "Poznań, ul. Długa 8",
    status: "unscheduled"
  },
  {
    id: "216",
    title: "CFM - Audi A4 2021",
    type: "CFM",
    stage: "Nowe zlecenie",
    scheduledDate: null,
    registrationNumber: "GD 11111",
    vin: "WAUZZZ8V5MA123456",
    brand: "Audi",
    model: "A4",
    year: "2021",
    color: "Szary",
    fuelType: "DIESEL",
    bodyType: "SEDAN",
    gearboxType: "AUTOMATYCZNA",
    mileage: "38000",
    clientFirstName: "Katarzyna",
    clientLastName: "Zielińska",
    clientPhone: "+48 601 234 567",
    clientEmail: "k.zielinska@biznes.pl",
    location: "Gdańsk, ul. Długa 15",
    status: "unscheduled"
  },
  {
    id: "217",
    title: "Wycena - Mercedes C-Class 2023",
    type: "WYCENA",
    stage: "Ustalone oględziny",
    scheduledDate: "2026-03-17T09:00:00",
    registrationNumber: "WR 22222",
    vin: "WDD2050341R123456",
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: "2023",
    color: "Niebieski",
    fuelType: "BENZYNA",
    bodyType: "SEDAN",
    gearboxType: "AUTOMATYCZNA",
    mileage: "12000",
    clientFirstName: "Tomasz",
    clientLastName: "Adamski",
    clientPhone: "+48 502 345 678",
    clientEmail: "t.adamski@firma.com",
    location: "Wrocław, ul. Świdnicka 3",
    status: "scheduled"
  }
]

export const MOCK_STAGES = [
  "Nowe zlecenie",
  "Ustalone oględziny", 
  "W trakcie inspekcji",
  "Zakończone",
  "Anulowane"
]
