/**
 * Next.js API Proxy — /api/protokol/[dealId]/pdf
 *
 * Streams the Protokół Wycena PDF generated by the FastAPI backend at
 * /protokol/{dealId}/pdf. The browser calls the same Next.js origin so
 * there are no CORS headaches and no URL expiry on the PDF link.
 */
import { NextRequest, NextResponse } from 'next/server';

const BACKEND = process.env.BACKEND_URL || 'http://backend:8000';

export async function GET(
  _req: NextRequest,
  { params }: { params: { dealId: string } },
) {
  const { dealId } = params;

  try {
    const res = await fetch(`${BACKEND}/protokol/${dealId}/pdf`, {
      cache: 'no-store',
    });

    if (!res.ok) {
      const text = await res.text();
      return NextResponse.json(
        { error: 'Backend error', status: res.status, detail: text },
        { status: res.status },
      );
    }

    const body = await res.arrayBuffer();
    return new NextResponse(body, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="protokol_wycena_${dealId}.pdf"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (err) {
    return NextResponse.json(
      { error: 'Backend unavailable', detail: String(err) },
      { status: 503 },
    );
  }
}
